name: test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [g++, clang++]
        exclude:
          - os: windows-latest
            compiler: g++

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Clang on Windows
        if: runner.os == 'Windows'
        run: choco install llvm -y

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          cmake --build build --config Release
        shell: bash
